.PHONY: all say_hello generate clean

all: say_hello generate

say_hello:
	@echo "Hello World"

generate:
	@echo "Creating Empty Text Files..."
	touch file-{1..10}.txt

clean:
	@echo "Cleaning up..."
	rm *.txt
